#!/usr/bin/env bash
shopt -s expand_aliases

source ~/.bashrc
set -e -o pipefail

##DOC up: Starts a new instance of the technology radar
goal_up() {
    goal_down
    docker-compose up -d --remove-orphans
    echo "Radar started. Open the page with the embedded file on http://localhost:8080/?sheetId=http%3A%2F%2Flocalhost%3A8080%2Fvtr.csv"
}

##DOC down: Stops a running instance of technology radar
goal_down() {
    docker-compose down
}

if type -t "goal_$1" &>/dev/null; then
  "goal_$1" "${@:2}"
else
  echo "usage: $0 <goal>"
  echo
  grep -e "^##DOC" <"$(basename "$0")" | sed "s/^##DOC \(.*\)/  \1/"
  echo
  exit 1
fi